### ISSUE TITLE
demo site alignment is off

### ISSUE THREAD

**Issue by ghost** [thedayhascome/Fluid-Baseline-Grid#1]
Hi
looks very promising, but the baseline on the demo site is not aligned with the background lines. Shouldn't that be the case?

**Comment by thedayhascome** [comment]
Yes, to truly place the grid at the baseline of the body text, the repeating background grid will need to be shifted down roughly 4px to align. Headings have slightly different margins and will never actually sit on the grid, which is designed to accommodate for appropriate breathing room above and below.

I'll make the necessary adjustments and update. Thanks for the input.

**Comment by thedayhascome** [comment]
v.1.0.1 released to align text baseline with grid_bg
