### ISSUE TITLE
decimal places in em units

### ISSUE THREAD

**Issue by krisbulman** [thedayhascome/Fluid-Baseline-Grid#2]
What is the benefit of using values with an extreme amount of decimal places in your vertical rhythm output: 

example: 1.1428571428571428571428571428571em

Is there any real difference from just using a rounded up number such as 1.143em ?

**Comment by thedayhascome** [comment]
The amount of decimals places to where browsers round is inconsistent. See John Resig's [Sub-Pixel Problems in CSS](http://ejohn.org/blog/sub-pixel-problems-in-css/).
Therefore, I prefer to give them all the information that I can, and let the browser choose how it rounds and handles the calculation.

With that being said, 3 decimals places would probably be sufficient. I just prefer to be _obsessively accurate_. It's also a technique inherited from Ethan Marcotte.

**Comment by krisbulman** [comment]
Thanks, the reason I ask is because I have been converting it to sass/compass & the included vertical rhythm mixins only support up to 3 decimal places. I have yet to check if it's possible to increase the amount of decimal places though.
