### ISSUE TITLE
IE 6-8 displaying content in one column.

### ISSUE THREAD

**Issue by TheScottSimpson** [thedayhascome/Fluid-Baseline-Grid#7]
This is a issue that has already been posted but there was no fix, fluidbaselinegrid.com works in IE 6-8 but the drupal demo site doesn't.  I have looked at other themes such as http://drupal.org/project/arctica and http://drupal.org/project/eclean they work and are doing so using respond.js and html5 shiv.

So am I missing something, I can't see how the theme link to html5 shiv, I've tried installing html5 tools module and that didn't work, I've changed the encoding to uft-8 without BOM and even put in doctype and add <head> linking to html5 shiv and still not working.

I've been searching for a answer to this for a good few weeks and have left issues on drupal and quora.
Are you working on a next release with this fix? 

This is by far the best theme for mark up, it's very compact and easy to modify for use and if I can have this little issue sorted it would make my year, seriously.

Please help

**Comment by thedayhascome** [comment]
I'm not responsible for the Drupal theme. That was created by someone using this framework as a starting point, so I'm not sure what has been modified.
