### ISSUE TITLE
Baseline not working, especially when scaling on Safari 7.1

### ISSUE THREAD

**Issue by ColeTownsend** [thedayhascome/Fluid-Baseline-Grid#9]
![screen shot 2014-10-20 at 6 57 22 pm](https://cloud.githubusercontent.com/assets/987654/4710640/a41aef84-58ac-11e4-9d4c-6b27e7f32ae3.png)

**Comment by thedayhascome** [comment]
The baseline works, but it is affected by the resizing of the logo image. This is not an issue, just a result of the image not scaling to the baseline. There are javascript workarounds to properly scaling any images to the set baseline height, as to not "throw-off" the full page rhythm.

**Comment by ColeTownsend** [comment]
Great! That's good to know.
